from . import hospital
from . import patient
from . import block
from . import admission
from . import inpatient_admission
from . import room
from . import bed
from . import pharmacy
from . import res_partner
from . import medicine
from . import medicine_box
from . import medicine_packing  
from . import medical_record
from . import prescription
from . import medical_record
from . import op_visit
from . import food
from . import block_duty
from . import configuration
from . import follow_up_sheet
from . import case_history
from . import outside_consultation
from . import patient_vaccine
from . import registration_form
from . import hospital_physician
from . import hospital_appointment
from . import hospital_evaluation
from . import medication_consent_form
from . import hospital_independent_examination
from . import hospital_caretaker_allotment
from . import hospital_laboratory
from . import hospital_room_inspection
from . import hospital_doctor_payout
from . import discharge
from . import activity_records
from . import nurse_assessment
# from . import case_history
from . import hospital_care_plan
from . import admission_referral_config
from . import hr_employee
from .import hospital_drug_chart
from . import models