{
    'name': 'FuturisticTech Medical',
    'version': '1.0',
    'summary': 'Comprehensive Medical Management System',
    'description': 'Module for managing hospitals, patients, doctors, and medical cases',
    'author': 'Elvice Ouma',
    'depends': ['base', 'mail', 'stock', 'account', 'hr'],
    'data': [
        'security/medical_security.xml',
        'security/ir.model.access.csv',
        'views/hospital_views.xml',
        'views/department_views.xml',
        'views/doctor_views.xml',
        'views/patient_views.xml',
        'views/medical_case_views.xml',
        'views/doctor_schedule_views.xml',
        'views/treatment_views.xml',
        'views/pharmacy_views.xml',
        'views/payment_views.xml',
        'views/res_partners.xml',
        'data/sequence.xml',
        'data/medical_data.xml',
        'report/medical_reports.xml',
        'report/report_templates.xml',

        'views/menu_views.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
