from . import hospital
from . import department
from . import doctor
from . import patient
from . import medical_case
from . import doctor_schedule
from . import treatment
from . import pharmacy
from . import payment
from . import medical_appointment
from . import res_partners
from . import physical_condition
from . import language_master
from . import services_master
from . import campus_master
from . import relationship_master
from . import medical_clinical_trail
from . import visits_activities
from . import customer_activity
from . import appointment_slot_link
from . import medical_registration_form
from . import medical_package
from . import crm_visits
from . import crm_lead
from . import crm_tags
from . import consultation
from . import consultation_prescription_line
from . import cross_consultation
from . import admission_models
from . import advice_models
from . import followup_wizard
from . import medical_labtest
from . import res_config_settings
from . import hr_employee
from . import oeh_models    
from . import sales_order
from . import sale_report
from . import slot_booking
from . import available_slot
from . import cancellation_policy
from . import cancellation_wizard