from . import hospital
from . import department
from . import doctor
from . import patient
from . import medical_case
from . import doctor_schedule
from . import treatment
from . import pharmacy
from . import payment
from . import medical_appointment
from . import  res_partners
from . import res_config_settings